kind: Secret
apiVersion: v1
metadata:
  name: expensereportdemo-secret
data:
  db-password: SW50M2dyNG4wdjQ=
  db-username: SW50ZWdyYW5vdmE=
type: Opaque
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: expensereportdemo-config
data:
  assignments-database-jdbc-url: 'jdbc:sqlserver://sotersqlserver.database.windows.net;databaseName=SOTER;encrypt=true'
  assignments-url: 'http://expreportdemo-ms-assignments:8084'
  operation-url: 'http://expreportdemo-ms-operation:8083'
  operation-database-jdbc-url: 'jdbc:sqlserver://sotersqlserver.database.windows.net;databaseName=SOTER;encrypt=true'
  agents-url: 'http://expreportdemo-ms-agents:8081'
  agents-database-jdbc-url: 'jdbc:sqlserver://sotersqlserver.database.windows.net;databaseName=SOTER;encrypt=true'
  expensereportdemo-url: 'http://expreportdemo-api-gateway:8080'
  masters-database-jdbc-url: 'jdbc:sqlserver://sotersqlserver.database.windows.net;databaseName=SOTER;encrypt=true'
  masters-url: 'http://expreportdemo-ms-masters:8082'
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: expreportdemo-ms-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expreportdemo-ms-agents
  template:
    metadata:
      labels:
        app: expreportdemo-ms-agents
    spec:
      containers:
        - name: expreportdemo-ms-agents
          image: expreportdemo-ms-agents:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
          - name: quarkus.datasource.jdbc.url
            valueFrom:
              configMapKeyRef:
                name: expensereportdemo-config
                key: operation-database-jdbc-url
          - name: quarkus.datasource.username
            valueFrom:
              secretKeyRef:
                name: expensereportdemo-secret
                key: db-username
          - name: quarkus.datasource.password
            valueFrom:
              secretKeyRef:
                name: expensereportdemo-secret
                key: db-password
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: expreportdemo-ms-agents
  labels:
    app: expensereportdemo-ms-agents
    app.kubernetes.io/component: expensereportdemo-ms-agents
    app.kubernetes.io/instance: expensereportdemo-ms-agents
    app.kubernetes.io/name: expensereportdemo-ms-agents
    app.kubernetes.io/part-of: expensereportdemo-app
    app.openshift.io/runtime: expensereportdemo-ms-agents
  annotation:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/jcarlosmolina/expreportdemo_ms_agents.git'
    isFromDevfile: 'true'
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  sesssionAffinity: None
  selector:
    app: expreportdemo-ms-agents
    deployment: expreportdemo-ms-agents
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: expreportdemo-ms-agents
  labels:
    app: expreportdemo-ms-agents
    app.kubernetes.io/component: expreportdemo-ms-agents
    app.kubernetes.io/instance: expreportdemo-ms-agents
    app.kubernetes.io/name: expreportdemo-ms-agents
    app.kubernetes.io/part-of: expensereportdemo-app
    app.openshift.io/runtime: expreportdemo-ms-agents
  annotations:
    isFromDevFile: 'true'
spec:
  host: expreportdemo-ms-agents-jcmintegranova-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
  to:
    kind: Service
    name: expreportdemo-ms-agents
    weight: 100
  port:
    targetPort: '8081'
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/jcarlosmolina/expreportdemo_ms_agents.git'
  name: expreportdemo-ms-agents
  labels:
    app: expreportdemo-ms-agents
    app.kubernetes.io/component: expreportdemo-ms-agents
    app.kubernetes.io/instance: expreportdemo-ms-agents
    app.kubernetes.io/name: expreportdemo-ms-agents
    app.kubernetes.io/part-of: expensereportdemo-app
    app.openshift.io/runtime: expreportdemo-ms-agents
spec:
  lookupPolicy:
    local: false
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: expreportdemo-ms-agents
  labels:
    app: expreportdemo-ms-agents
    app.kubernetes.io/component: expreportdemo-ms-agents
    app.kubernetes.io/instance: expreportdemo-ms-agents
    app.kubernetes.io/name: expreportdemo-ms-agents
    app.kubernetes.io/part-of: expensereportdemo-app
    app.openshift.io/runtime: expreportdemo-ms-agents
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'expreportdemo-ms-agents:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: src/main/docker/Dockerfile.jvm.staged
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/jcarlosmolina/expreportdemo_ms_agents.git'
  runPolicy: Serial
